### ISSUE TITLE
Please create an official license for natbeat

### ISSUE THREAD

**Issue by jdeppe-pivotal** [cloudfoundry-incubator/natbeat#4]
Lawyers really want to see licenses for OSS code. It makes then feel warm and fuzzy.

**Comment by ematpl** [comment]
Thanks, @jdeppe-pivotal! We'll take care of that as soon as possible.

Thanks again,
Eric, CF Runtime Diego PM

**Comment by fraenkel** [comment]
An Apache 2.0 License has been added

**Comment by jdeppe-pivotal** [comment]
Thanks for the quick response!
